// Fixture data 
if(MemoryVerses.find().count() === 0) {
  
	//the verses
	var theVerses = [{  "month":2, "reference": "Romans 12:9-11 (NKJV)", "text": "Let love be without hypocrisy. Abhor what is evil. Cling to what is good. Be kindly affectionate to one another with brotherly love, in honor giving preference to one another; not lagging in diligence, fervent in spirit, serving the Lord;", "year": "BOOKS"  },
		{  "month":3, "reference": "Jeremiah 9:23-24 (NKJV)", "text": "Thus says the Lord: Let not the wise man glory in his wisdom, Let not the mighty man glory in his might, Nor let the rich man glory in his riches; But let him who glories glory in this, That he understands and knows Me, That I am the Lord, exercising lovingkindness, judgment, and righteousness in the earth. For in these I delight says the Lord.", "year": "BOOKS"  },
		{  "month":4, "reference": "1 Chronicles 29:11-12 (NKJV)", "text": "Yours, O Lord, is the greatness, The power and the glory, The victory and the majesty; For all that is in heaven and in earth is Yours; Yours is the kingdom, O Lord, And You are exalted as head over all. Both riches and honor come from You, And You reign over all. In Your hand is power and might; In Your hand it is to make great And to give strength to all.", "year": "BOOKS"  },
		{  "month":5, "reference": "Psalm 73:25-28 (NKJV)", "text": "Whom have I in heaven but You? And there is none upon earth that I desire besides You. My flesh and my heart fail; But God is the strength of my heart and my portion forever. For indeed, those who are far from You shall perish; You have destroyed all those who desert You for harlotry. But it is good for me to draw near to God; I have put my trust in the Lord GOD, That I may declare all Your works.", "year": "BOOKS" },
		{ "month":6, "reference": "1 Corinthians 15:10 (NKJV)", "text": "But by the grace of God I am what I am, and His grace toward me was not in vain; but I labored more abundantly than they all, yet not I, but the grace of God which was with me.", "year": "BOOKS" },
		{ "month":7, "reference": "Hebrews 12:1-4 (NKJV)", "text": "Therefore we also, since we are surrounded by so great a cloud of witnesses, let us lay aside every weight, and the sin which so easily ensnares us, and let us run with endurance the race that is set before us, looking unto Jesus, the author and finisher of our faith, who for the joy that was set before Him endured the cross, despising the shame, and has sat down at the right hand of the throne of God. For consider Him who endured such hostility from sinners against Himself, lest you become weary and discouraged in your souls. You have not yet resisted to bloodshed, striving against sin.", "year": "BOOKS" },
		{ "month":8, "reference": "1 Peter 3:14-17 (NKJV)", "text": "But even if you should suffer for righteousness sake, you are blessed. And do not be afraid of their threats, nor be troubled. But sanctify the Lord God in your hearts, and always be ready to give a defense to everyone who asks you a reason for the hope that is in you, with meekness and fear; having a good conscience, that when they defame you as evildoers, those who revile your good conduct in Christ may be ashamed. For it is better, if it is the will of God, to suffer for doing good than for doing evil.", "year": "BOOKS" },
		{ "month":9, "reference": "1 Peter 3:7 (NKJV)", "text": "Husbands, likewise, dwell with them with understanding, giving honor to the wife, as to the weaker vessel, and as being heirs together of the grace of life, that your prayers may not be hindered.", "year": "BOOKS" },
		{ "month":10, "reference": "Ephesians 6:4 (NKJV)", "text": "And you, fathers, do not provoke your children to wrath, but bring them up in the training and admonition of the Lord.", "year": "BOOKS" },
		{ "month":11, "reference": "1 Timothy 4:7-8 (NIV)", "text": "Have nothing to do with godless myths and old wives' tales; rather, train yourself to be godly. For physical training is of some value, but godliness has value for all things, holding promise for both the present life and the life to come.", "year": "BOOKS" },
		{ "month":2, "reference": "Psalms. 1:1-2", "text": "Blessed is the man who walks not in the counsel of the wicked, nor stands in the way of sinners, nor sits in the seat of scoffers; but his delight is in the law of the LORD, and on his law he meditates day and night.", "year": "GRUDEM" },
		{ "month":2, "reference": "2 Timothy 3:16-17 (NKJV)", "text": "All Scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness, that the man of God may be complete, thoroughly equipped for every good work.", "year": "GRUDEM" },
		{ "month":3, "reference": "Exodus 33:13-15", "text": "Now therefore, I pray, if I have found grace in Your sight, show me now Your way, that I may know You and that I may find grace in Your sight. And consider that this nation is Your people. And He said, My Presence will go with you, and I will give you rest.  Then he said to Him, If Your Presence does not go with us, do not bring us up from here.", "year": "GRUDEM" },
		{ "month":3, "reference": "Romans 1:18-20", "text": "The wrath of God is being revealed from heaven against all the godlessness and wickedness of men who suppress the truth by their wickedness, since what may be known about God is plain to them, because God has made it plain to them. For since the creation of the world God's invisible qualities--his eternal power and divine nature--have been clearly seen, being understood from what has been made, so that men are without excuse.", "year": "GRUDEM" },
		{ "month":4, "reference": "Romans 8:28-29 (NKJV)", "text": "And we know that all things work together for good to those who love God, to those who are the called according to His purpose. For whom He foreknew, He also predestined to be conformed to the image of His Son, that He might be the first born among many brethren.", "year": "GRUDEM" },
		{ "month":4, "reference": "Psalm 115:3", "text": "But our God is in heaven; He does whatever He pleases.", "year": "GRUDEM" },
		{ "month":4, "reference": "Job 42:2 (NKJV)", "text": "I know that You can do everything, and that no purpose of Yours can be withheld from You.", "year": "GRUDEM" },
		{ "month":5, "reference": "Nehemiah 9:6", "text": "And Ezra said: 'You are the LORD, you alone; you have made heaven, the heaven of heavens, with all their host, the earth and all that is on it, the seas and all that is in them; and you preserve all of them; and the host of heaven worships you.'", "year": "GRUDEM" },
		{ "month":6, "reference": "Colossians 3:18-19", "text": "Wives, submit to your own husbands, as is fitting in the Lord.  Husbands, love your wives and do not be bitter toward them.", "year": "GRUDEM" },
		{ "month":6, "reference": "Ephesians 2:1-5", "text": "And you He made alive who were dead in trespasses ands sins, in which you formerly walked according to the course of this world, according to the prince of the power of the air, the spirit who now works in the sons of disobedience, among whom also we all once conducted ourselves in the lusts of our flesh, fulfilling the desires of the flesh and of the mind, and were by nature children of wrath, just as the others.  But God, who is rich in mercy, because of His great love with which He loved us, even when we were dead in trespasses made us alive together with Christ (by grace you have been saved).", "year": "GRUDEM" },
		{ "month":7, "reference": "John 1:14", "text": "And the Word became flesh and dwelt among us, and we beheld His glory, the glory as of the only begotten of the Father, full of grace and truth.", "year": "GRUDEM" },
		{ "month":7, "reference": "Romans 3:23-24", "text": "For all have sinned and fall short of the glory of God, being justified freely by His grace through the redemption that is in Christ Jesus.", "year": "GRUDEM" },
		{ "month":8, "reference": "Galatians 2:20 (NKJV)", "text": "I have been crucified with Christ; it is no longer I who live, but Christ lives in me; and the life which I now live in the flesh I live by faith in the Son of God, who loved me and gave Himself for me.", "year": "GRUDEM" },
		{ "month":8, "reference": "John 10:27-28 (NKJV)", "text": "My sheep hear My voice, and I know them and they follow Me.  And I give them eternal life, and they shall never perish; neither shall anyone snatch them out of My hand.", "year": "GRUDEM" },
		{ "month":9, "reference": "James 4:7-8 (NKJV)", "text": "Therefore, submit to God.  Resist the devil and he will flee from you.  Draw near to God and He will draw near to you.  Cleanse your hands, you sinners; and purify your hearts, you double-minded.", "year": "GRUDEM" },
		{ "month":10, "reference": "Ephesians 1:3-6", "text": "Blessed be the God and Father of our Lord Jesus Christ, who has blessed us with every spiritual blessing in the heavenly places in Christ, just as He chose us in Him before the foundation of the world, that we should be holy and without blame before Him in love, having predestined us to adoption as sons by Jesus Christ to Himself, according to the good pleasure of His will, to the praise of the glory of His grace, by which He has made us accepted in the Beloved.", "year": "GRUDEM" },
		{ "month":11, "reference": "2 Corinthians 5:9-10 (NKJV)", "text": "Therefore we make it our aim, whether present or absent, to be well pleasing to Him.  For we must all appear before the judgment seat of Christ, that each one may receive the things done in the body, according to what he has done, whether good or bad.", "year": "GRUDEM" }
	];

	for(var i=0;i<theVerses.length;i++){
		// create a verse
		MemoryVerses.insert(
			 theVerses[i]
		);
	}
}

if(PrayerRequests.find().count() === 0){
	//default prayer requests
	var theRequests = [{"categoryNumber":1, "category":"Church Staff" , "request":"Pastor Brad and his family, Pastor Peter Laruffa and his family, Pastor Bob and his family, Pastor Ken and family, Lee Nordine and family, Todd Richmond and family, Syl Masih and family, Tyson Ziegler and family, Brad Spence and family, Bob Smith and family, Ryan Fultz and family; Aaron Barnett and (Eliza) family; Admin staff: Jackie, David, Erin, Laura, Lisa, Megan, and Jennifer Ortenzi; Elders and families: Rob Lohrmann, Roger Patterson, Brian Fannin, and J.D. Rogers. Deacons and families: Steve Lee, Ben Townsend, Jerry Nash, Willie Schadler, Tim Waits, Rique DeWald, Steve Johnston, Kevin Markesberry, Lloyd Conely and Doug Ortenzi . Sunday School Teachers, Worship Team, for the Small Groups and the leaders and what takes place in them. Your will done there God, indeed and always!"},
		{"categoryNumber":2, "category":"Coworkers" , "request":"Lynn Richardson, Dan O'Connor, Lance Faig, Brad Snelling, and Brad Berding."},
		{"categoryNumber":3, "category":"Extended Family" , "request":"For their salvation as a model of Your grace. If not, then their lives to Your glory; Mom and Jim; Jesse and Cheryl, Josh and Kim ; Dale and Danita, Dustin, Erin; Doug, Garrett, and Benjamin; Rusty and Tim and families; Debbie and Jared; Chris and Tim, Erin; Lori and Mike, C.J., Carlee, Rayder & Eli; Zach and family, Tiff and family, Timmy and family; Mimi-her back and side and skin on her arm, Sharon and Eric, Tiffany and Nathan, Kearsten and Trevor, and Family; Becky, Cheryl, Steve and families; Ed and Barb, Rod and Mary Dawn, and Hailey, Scott and Buffy, Tyler, Tanner, Christy; Aunt Carol, Bruce and Betsy, Jonathon and Jamie, and the baby; Amanda, Donna, Holly, Scott, Craig, and families; Kristi, Jason, and Sophya."},
		{"categoryNumber":4, "category":"Federal Government" , "request":"'The king's heart is a stream of water in the hand of the LORD; he turns it wherever he will.' Proverbs 21:1 President Obama, Vice-President Biden, Cabinet, Dept. Heads, Advisors, Military Leaders and all personnel, Senate, House of Representatives, Supreme Court, Federal Courts."},
		{"categoryNumber":5, "category":"Immediate Family" , "request":"Your good hand upon us God; Jackie - glorifying you, health, safety, well being, Your will in her life, and joy. Her eyes and feet problems. For strength for dealing with life, her job, and me. That she have proper motivations and wisdom; Seth - his salvation and becoming a productive member of society; John & Alyse - John for his intestinal problems; their goals be Biblically motivated and give them wisdom, restraint, foresight in their home and work life; children. To grow in their marriage. Motivation for them to do all things to your glory God.; We all need proper selections in what we hear and view. Sophya and her safety and salvation."},
		{"categoryNumber":6, "category":"Individuals" , "request":"Persecuted Church Worldwide, Tyson and Deb Zigler; Teresa and Benjamin; Teresa, salvation and relationships. Keith and Mariah Winchester. Mitsu and Kristin Nakamura. That doors open to relationships with international students as well as the Curd's leadership. For men at Pure Life now. As the Lord brings us to mind, would you please pray for the following: ~ That the Lord will guard me against fear and help me to meditate  on  His sovereign control over all things--including _______________. That the Lord will enable me to continue to put off self-pity and to put on gratitude.That the Lord will keep me praying for the needs of others and not myself only. For wisdom with present and future commitments. Meditating on His sovereignty has brought such peace. He limits,\orders, controls, and knows all about every aspect of our lives. What rich comfort this brings. Job 38:8-11 'Or who shut in the sea with doors, when it burst forth and issued from the womb; when I made the clouds its garment, and thick darkness its swaddling band; when I fixed My limit for it, and set bars and doors; when I said, 'This far you may come, but no farther, and here your proud waves must stop!'"},
		{"categoryNumber":7, "category":"IOUS" , "request":"Inclination toward God and His word - Ps 119:36-37 - 'Incline my heart to your testimonies, and not to selfish gain! Turn my eyes from looking at worthless things; and give me life in your ways.' Opened eyes - Psalm 119:18 - 'Open my eyes, that I may behold wondrous things out of your law.' United heart - Psalm 86:11 - 'Teach me your way, O LORD, that I may walk in your truth; unite my heart to fear your name.' Satisfaction in the Lord - Psalm 90:14 - 'Satisfy us in the morning with your steadfast love, that we may rejoice and be glad all our days.'"},
		{"categoryNumber":8, "category":"Joshua's Men" , "request":"James Geyer, Ron Uebel, Shawn Blankenship, Steve Ham, Andrew Caudill, Wes Layne, Jimmy Marshall, John Bartlett, Sr., Josh Anderson, and David Michael."},
		{"categoryNumber":9, "category":"Local Government" , "request":"'The king's heart is a stream of water in the hand of the LORD; he turns it wherever he will.' Proverbs 21:1 City Managers, Mayors, Council Members, Police, Sheriff and Deputies, Local Courts of Erlanger, Independence, Florence, Edgewood, Crestview Hills, Ft. Mitchell, Ft. Wright, Covington, Newport, Cincinnati, and other local towns.; County Governments of Northern KY, Southwestern OH, and Southeastern IN."},
		{"categoryNumber":10, "category":"Me" , "request":"That I may glorify God and enjoy Him forever! To be aware of the inner dialog that takes place minute by minute and to correctly understand it and correct it. To do as the Psalmist did and tell my soul to bless the Lord and to hope in God."},
		{"categoryNumber":11, "category":"Missions" , "request":"This week we're praying for our own Doug and Diane Markesbery who serve in Timisoara, Romania. Monday: 'Behold, I am the Lord, the God of all flesh.  Is anything too hard for me?' These were God's words to Jeremiah when he saw no hope for his country. (Jeremiah 32:27).  God continues to prove that there is nothing too hard for Him. As you pray for us this week, we encourage you to remember there is nothing too hard for God. Pray big prayers, and pray with great faith!  Start the week by joining us in praising God for taking care of us through an emergency appendectomy for Diane.  She is still a little sore, but she is healing well. Tuesday: Pray for Module 6 of our Biblical Counseling School.  Dr. Mark Shaw from Faith Baptist in Lafayette, IN. will be instructing us in how to counsel those with sinful habits (addictions).  November 14-15 (Friday/Saturday). Pray for the students to understand and learn skills for ministering God's Word to people with this need. These students are on the front lines in the war against evil in our world.  Pray that God will use them to proclaim His word and transform many lives for His glory! Wednesday: Sunday, Nov. 16, Dr. Shaw will be leading a mini conference on sexual sin focusing on the issue of pornography.  Satan is using this evil to destroy marriages, families, personal lives, and churches!  For the first time we will present this conference in a local church.  Please pray for God to do miracles in the hearts and lives of the people of this church. Pray for God to break the yoke of lust and fill hearts with His love!Thursday:  Saturday/Sunday (Nov. 22-23), Doug will be teaching at a Leadership Retreat for Men in Bucharest (the capitol city of Romania).  Please pray for Doug and the men who will be attending.  Pray for God to strengthen these men to be Godly leaders in their homes and in the church!  Pray that God will continue to prepare my heart and mind to effectively lead these men.Friday: Jesus taught us to pray, 'lead us not into temptation, but deliver us from evil'.  Please pray for me and Diane that God will keep us from all evil; that God will keep our marriage strong and pure; that God will enable us to understand His plan and purpose for ministry here; that we will love Him with all of our heart, mind, soul, and strength; and love our neighbors as ourselves. Saturday/Sunday: Grace Fellowship is blessed to have a strong Biblical counseling ministry.  GFC is now working to build this ministry in the evangelical churches of Romania.  The training has gone well so far.  But now we must 'cross the river' of getting this ministry established in the churches. Please pray that God will 'lead us through on dry ground' and establish this much-needed ministry in the local churches."},
		{"categoryNumber":12, "category":"Neighbors" , "request":"Matt and Kelly, Jack and Kathy, Larry and Diane, Lisa and Mark, new neighbors across the street, the family that will be moving into Lonnie's, Gary and Virgina, George and Bev, Tomia, Chuck, Francois and Angie, and Bill and Joan and their family members. I pray for the salvation, earthly well being and our harmony with them in the neighborhood."},
		{"categoryNumber":13, "category":"Skills" , "request":"But seek first the kingdom of God and his righteousness, and all these things will be added to you. (Matt. 6:33) Help me to seek first your kingdom Lord and not mine. Give me proper motivation for skill--life, Biblical, and professional--for your kingdom and glory, and the ability to get the skills. Balanced study according to Your will Lord."},
		{"categoryNumber":14, "category":"Small Group" , "request":"Direction of the topics, discussion, what is done, and who attends. For the following and their families: Daniel and Brittany Allison, Zach Briggs, Lewis and Megan Curd, Cole Mitchell, Anthony Mullis, Rachel  Nieboer, Austin  Richardson, Michael and Camden Ritchie, and Lisa Van Berkel; For God to direct who, what, when, why, and where He wants for the group."},
		{"categoryNumber":15, "category":"State Government" , "request":"'The king's heart is a stream of water in the hand of the LORD; he turns it wherever he will.' Proverbs 21:1 Kentucky, Ohio, and Indiana Govenors, Legislature, State Courts, State Militia, Law Enforcement."},
		{"categoryNumber":16, "category":"World Situation" , "request":"Persecuted Church Worldwide, National governments and tribal (local) regions open to the gospel. God's ultimate will to be done in each nation state around the world. I hope you all are well."}
	];
		
	for(var i=0;i<theRequests.length;i++){
		// create a request
		PrayerRequests.insert(
			 theRequests[i]
		);
	}
}

if(WestminsterCatechisms.find().count() === 0){
	//default catechism Q/A
	var theCatechisms = [{"number":"1" , "question":"What is the chief end of man?", "answer":"To glorify God and enjoy Him forever"},
		{"number":"2" , "question":"What rule hath God given to direct us how we may glorify and enjoy him?", "answer":"The word of God, which is contained in the scriptures of the Old and New Testaments, is the only rule to direct us how we may glorify and enjoy him."},
		{"number":"3" , "question":"What do the scriptures principally teach?", "answer":"The scriptures principally teach what man is to believe concerning God, and what duty God requires of man."},
		{"number":"4" , "question":"What is God?", "answer":"God is a spirit, infinite, eternal, and unchangeable, in his being, wisdom, power, holiness, justice, goodness and truth."},
		{"number":"5" , "question":"Are there more Gods than one?", "answer":"There is but one only, the living and true God."},
		{"number":"6" , "question":"How many persons are there in the godhead?", "answer":"There are three persons in the Godhead; the Father, the Son, and the Holy Ghost; and these three are one God, the same in substance, equal in power and glory."},
		{"number":"7" , "question":"What are the decrees of God?", "answer":"The decrees of God are his eternal purpose, according to the counsel of his will, whereby, for his own glory, he hath foreordained whatsoever comes to pass."},
		{"number":"8" , "question":"How doth God execute his decrees?", "answer":"God executeth his decrees in the works of creation and providence."},
		{"number":"9" , "question":"What is the work of creation?", "answer":"The work of creation is God's making all things of nothing, by the word of his power, in the space of six days, and all very good."},
		{"number":"10" , "question":"How did God create man?", "answer":"God created man male and female, after his own image, in knowledge, righteousness and holiness, with dominion over the creatures."},
		{"number":"11" , "question":"What are God's works of providence?", "answer":"God's works of providence are his most holy, wise and powerful preserving and governing all his creatures, and all their actions."},
		{"number":"12" , "question":"What special act of providence did God exercise toward man in the estate wherein he was created?", "answer":"When God had created man, he entered into a covenant of life with him, upon condition of perfect obedience; forbidding him to eat of the tree of the knowledge of good and evil, upon the pain of death."},
		{"number":"13" , "question":"Did our first parents continue in the estate wherein they were created?", "answer":"Our first parents, being left to the freedom of their own will, fell from the estate wherein they were created, by sinning against God."},
		{"number":"14" , "question":"What is sin?", "answer":"Sin is any want of conformity unto, or transgression of, the law of God."},
		{"number":"15" , "question":"What was the sin whereby our first parents fell from the estate wherein they were created?", "answer":"The sin whereby our first parents fell from the estate wherein they were created was their eating the forbidden fruit."},
		{"number":"16" , "question":"Did all mankind fall in Adam's first transgression?", "answer":"The covenant being made with Adam, not only for himself, but for his posterity; all mankind, descending from him by ordinary generation, sinned in him, and fell with him, in his first transgression."},
		{"number":"17" , "question":"Into what estate did the fall bring mankind?", "answer":"The fall brought mankind into an estate of sin and misery."},
		{"number":"18" , "question":"Wherein consists the sinfulness of that estate whereinto man fell?", "answer":"The sinfulness of that estate whereinto man fell consists in the guilt of Adam's first sin, the want of original righteousness, and the corruption of his whole nature, which is commonly called original sin; together with all actual transgressions which proceed from it."},
		{"number":"19" , "question":"What is the misery of that estate whereinto man fell?", "answer":"All mankind by their fall lost communion with God, are under his wrath and curse, and so made liable to all miseries in this life, to death itself, and to the pains of hell forever."},
		{"number":"20" , "question":"Did God leave all mankind to perish in the estate of sin and misery?", "answer":"God having, out of his mere good pleasure, from all eternity, elected some to everlasting life, did enter into a covenant of grace, to deliver them out of the estate of sin and misery, and to bring them into an estate of salvation by a redeemer."},
		{"number":"21" , "question":"Who is the redeemer of God's elect?", "answer":"The only redeemer of God's elect is the Lord Jesus Christ, who, being the eternal Son of God, became man, and so was, and continueth to be, God and man in two distinct natures, and one person, forever."},
		{"number":"22" , "question":"How did Christ, being the Son of God, become man?", "answer":"Christ, the Son of God, became man, by taking to himself a true body and a reasonable soul, being conceived by the power of the Holy Ghost in the womb of the virgin Mary, and born of her, yet without sin."},
		{"number":"23" , "question":"What offices doth Christ execute as our redeemer?", "answer":"Christ, as our redeemer, executeth the offices of a prophet, of a priest, and of a king, both in his estate of humiliation and exaltation."},
		{"number":"24" , "question":"How doth Christ execute the office of a prophet?", "answer":"Christ executeth the office of a prophet, in revealing to us, by his word and Spirit, the will of God for our salvation."},
		{"number":"25" , "question":"How doth Christ execute the office of a priest?", "answer":"Christ executeth the office of a priest, in his once offering up of himself a sacrifice to satisfy divine justice, and reconcile us to God; and in making continual intercession for us."},
		{"number":"26" , "question":"How doth Christ execute the office of a king?", "answer":"Christ executeth the office of a king, in subduing us to himself, in ruling and defending us, and in restraining and conquering all his and our enemies."},
		{"number":"27" , "question":"Wherein did Christ's humiliation consist?", "answer":"Christ's humiliation consisted in his being born, and that in a low condition, made under the law, undergoing the miseries of this life, the wrath of God, and the cursed death of the cross; in being buried, and continuing under the power of death for a time."},
		{"number":"29" , "question":"How are we made partakers of the redemption purchased by Christ?", "answer":"We are made partakers of the redemption purchased by Christ, by the effectual application of it to us by his Holy Spirit."},
		{"number":"28" , "question":"Wherein consisteth Christ's exaltation?", "answer":"Christ's exaltation consisteth in his rising again from the dead on the third day, in ascending up into heaven, in sitting at the right hand of God the Father, and in coming to judge the world at the last day."},
		{"number":"30" , "question":"How doth the Spirit apply to us the redemption purchased by Christ?", "answer":"The Spirit applieth to us the redemption purchased by Christ, by working faith in us, and thereby uniting us to Christ in our effectual calling."},
		{"number":"31" , "question":"What is effectual calling?", "answer":"Effectual calling is the work of God's Spirit, whereby, convincing us of our sin and misery, enlightening our minds in the knowledge of Christ, and renewing our wills, he doth persuade and enable us to embrace Jesus Christ, freely offered to us in the gospel."},
		{"number":"32" , "question":"What benefits do they that are effectually called partake of in this life?", "answer":"They that are effectually called do in this life partake of justification, adoption and sanctification, and the several benefits which in this life do either accompany or flow from them."},
		{"number":"33" , "question":"What is justification?", "answer":"Justification is an act of God's free grace, wherein he pardoneth all our sins, and accepteth us as righteous in his sight, only for the righteousness of Christ imputed to us, and received by faith alone."},
		{"number":"34" , "question":"What is adoption?", "answer":"Adoption is an act of God's free grace, whereby we are received into the number, and have a right to all the privileges of, the sons of God."},
		{"number":"35" , "question":"What is sanctification?", "answer":"Sanctification is the work of God's free grace, whereby we are renewed in the whole man after the image of God, and are enabled more and more to die unto sin, and live unto righteousness."},
		{"number":"36" , "question":"What are the benefits which in this life do accompany or flow from justification, adoption and sanctification?", "answer":"The benefits which in this life do accompany or flow from justification, adoption and sanctification, are, assurance of God's love, peace of conscience, joy in the Holy Ghost, increase of grace, and perseverance therein to the end."},
		{"number":"37" , "question":"What benefits do believers receive from Christ at death?", "answer":"The souls of believers are at their death made perfect in holiness, and do immediately pass into glory; and their bodies, being still united to Christ, do rest in their graves till the resurrection."},
		{"number":"38" , "question":"What benefits do believers receive from Christ at the resurrection?", "answer":"At the resurrection, believers being raised up in glory, shall be openly acknowledged and acquitted in the day of judgment, and made perfectly blessed in the full enjoying of God to all eternity."},
		{"number":"39" , "question":"What is the duty which God requireth of man?", "answer":"The duty which God requireth of man is obedience to his revealed will."},
		{"number":"40" , "question":"What did God at first reveal to man for the rule of his obedience?", "answer":"The rule which God at first revealed to man for his obedience was the moral law."},
		{"number":"41" , "question":"Where is the moral law summarily comprehended?", "answer":"The moral law is summarily comprehended in the ten commandments."},
		{"number":"42" , "question":"What is the sum of the ten commandments?", "answer":"The sum of the ten commandments is to love the Lord our God with all our heart, with all our soul, with all our strength, and with all our mind; and our neighbor as ourselves."},
		{"number":"43" , "question":"What is the preface to the ten commandments?", "answer":"The preface to the ten commandments is in these words, I am the Lord thy God, which have brought thee out of the land of Egypt, out of the house of bondage."},
		{"number":"44" , "question":"What doth the preface to the ten commandments teach us?", "answer":"The preface to the ten commandments teacheth us that because God is the Lord, and our God, and redeemer, therefore we are bound to keep all his commandments."},
		{"number":"45" , "question":"Which is the first commandment?", "answer":"The first commandment is, Thou shalt have no other gods before me."},
		{"number":"46" , "question":"What is required in the first commandment?", "answer":"The first commandment requireth us to know and acknowledge God to be the only true God, and our God; and to worship and glorify him accordingly."},
		{"number":"47" , "question":"What is forbidden in the first commandment?", "answer":"The first commandment forbiddeth the denying, or not worshiping and glorifying the true God as God, and our God; and the giving of that worship and glory to any other, which is due to him alone."},
		{"number":"48" , "question":"What are we specially taught by these words before me in the first commandment?", "answer":"These words before me in the first commandment teach us that God, who seeth all things, taketh notice of, and is much displeased with, the sin of having any other god."},
		{"number":"49" , "question":"Which is the second commandment?", "answer":"The second commandment is, Thou shalt not make unto thee any graven image, or any likeness of anything that is in heaven above, or that is in the earth beneath, or that is in the water under the earth: thou shalt not bow down thyself to them, nor serve them: for I the Lord thy God am a jealous God, visiting the iniquity of the fathers upon the children unto the third and fourth generation of them that hate me; and showing mercy unto thousands of them that love me, and keep my commandments."},
		{"number":"50" , "question":"What is required in the second commandment?", "answer":"The second commandment requireth the receiving, observing, and keeping pure and entire, all such religious worship and ordinances as God hath appointed in his word."},
		{"number":"51" , "question":"What is forbidden in the second commandment?", "answer":"The second commandment forbiddeth the worshiping of God by images, or any other way not appointed in his word."},
		{"number":"52" , "question":"What are the reasons annexed to the second commandment?", "answer":"The reasons annexed to the second commandment are, God's sovereignty over us, his propriety in us, and the zeal he hath to his own worship."},
		{"number":"53" , "question":"Which is the third commandment?", "answer":"The third commandment is, Thou shalt not take the name of the Lord thy God in vain: for the Lord will not hold him guiltless that taketh his name in vain."},
		{"number":"54" , "question":"What is required in the third commandment?", "answer":"The third commandment requireth the holy and reverent use of God's names, titles, attributes, ordinances, word and works."},
		{"number":"55" , "question":"What is forbidden in the third commandment?", "answer":"The third commandment forbiddeth all profaning or abusing of anything whereby God maketh himself known."},
		{"number":"56" , "question":"What is the reason annexed to the third commandment?", "answer":"The reason annexed to the third commandment is that however the breakers of this commandment may escape punishment from men, yet the Lord our God will not suffer them to escape his righteous judgment."},
		{"number":"57" , "question":"Which is the fourth commandment?", "answer":"The fourth commandment is, Remember the sabbath day, to keep it holy. Six days shalt thou labor, and do all thy work: but the seventh day is the sabbath of the Lord thy God: in it thou shalt not do any work, thou, nor thy son, nor thy daughter, thy manservant, nor thy maidservant, nor thy cattle, nor thy stranger that is within thy gates: for in six days the Lord made heaven and earth, the sea, and all that in them is, and rested the seventh day: wherefore the Lord blessed the sabbath day, and hallowed it."},
		{"number":"58" , "question":"What is required in the fourth commandment?", "answer":"The fourth commandment requireth the keeping holy to God such set times as he hath appointed in his word; expressly one whole day in seven, to be a holy sabbath to himself."},
		{"number":"59" , "question":"Which day of the seven hath God appointed to be the weekly sabbath?", "answer":"From the beginning of the world to the resurrection of Christ, God appointed the seventh day of the week to be the weekly sabbath; and the first day of the week ever since, to continue to the end of the world, which is the Christian sabbath."},
		{"number":"60" , "question":"How is the sabbath to be sanctified?", "answer":"The sabbath is to be sanctified by a holy resting all that day, even from such worldly employments and recreations as are lawful on other days; and spending the whole time in the public and private exercises of God's worship, except so much as is to be taken up in the works of necessity and mercy."},
		{"number":"92" , "question":"What is a sacrament?", "answer":"A sacrament is an holy ordinance instituted by Christ; wherein, by sensible signs, Christ, and the benefits of the new covenant, are represented, sealed, and applied to believers."},
		{"number":"61" , "question":"What is forbidden in the fourth commandment?", "answer":"The fourth commandment forbiddeth the omission or careless performance of the duties required, and the profaning the day by idleness, or doing that which is in itself sinful, or by unnecessary thoughts, words or works, about our worldly employments or recreations."},
		{"number":"62" , "question":"What are the reasons annexed to the fourth commandment?", "answer":"The reasons annexed to the fourth commandment are, God's allowing us six days of the week for our own employments, his challenging a special propriety in the seventh, his own example, and his blessing the sabbath day."},
		{"number":"63" , "question":"Which is the fifth commandment?", "answer":"The fifth commandment is, Honor thy father and thy mother; that thy days may be long upon the land which the Lord thy God giveth thee."},
		{"number":"64" , "question":"What is required in the fifth commandment?", "answer":"The fifth commandment requireth the preserving the honor, and performing the duties, belonging to every one in their several places and relations, as superiors, inferiors or equals."},
		{"number":"65" , "question":"What is forbidden in the fifth commandment?", "answer":"The fifth commandment forbiddeth the neglecting of, or doing anything against, the honor and duty which belongeth to every one in their several places and relations."},
		{"number":"66" , "question":"What is the reason annexed to the fifth commandment?", "answer":"The reason annexed to the fifth commandment is a promise of long life and prosperity (as far as it shall serve for God's glory and their own good) to all such as keep this commandment."},
		{"number":"67" , "question":"Which is the sixth commandment?", "answer":"The sixth commandment is, Thou shalt not kill."},
		{"number":"68" , "question":"What is required in the sixth commandment?", "answer":"The sixth commandment requireth all lawful endeavors to preserve our own life, and the life of others."},
		{"number":"69" , "question":"What is forbidden in the sixth commandment?", "answer":"The sixth commandment forbiddeth the taking away of our own life, or the life of our neighbor unjustly, or whatsoever tendeth thereunto."},
		{"number":"70" , "question":"Which is the seventh commandment?", "answer":"The seventh commandment is, Thou shalt not commit adultery."},
		{"number":"71" , "question":"What is required in the seventh commandment?", "answer":"The seventh commandment requireth the preservation of our own and our neighbor's chastity, in heart, speech and behavior."},
		{"number":"72" , "question":"What is forbidden in the seventh commandment?", "answer":"The seventh commandment forbiddeth all unchaste thoughts, words and actions."},
		{"number":"73" , "question":"Which is the eighth commandment?", "answer":"The eighth commandment is, Thou shalt not steal."},
		{"number":"74" , "question":"What is required in the eighth commandment?", "answer":"The eighth commandment requireth the lawful procuring and furthering the wealth and outward estate of ourselves and others."},
		{"number":"75" , "question":"What is forbidden in the eighth commandment?", "answer":"The eighth commandment forbiddeth whatsoever doth or may unjustly hinder our own or our neighbor's wealth or outward estate."},
		{"number":"76" , "question":"Which is the ninth commandment?", "answer":"The ninth commandment is, Thou shalt not bear false witness against thy neighbor."},
		{"number":"77" , "question":"What is required in the ninth commandment?", "answer":"The ninth commandment requireth the maintaining and promoting of truth between man and man, and of our own and our neighbor's good name, especially in witness-bearing."},
		{"number":"78" , "question":"What is forbidden in the ninth commandment?", "answer":"The ninth commandment forbiddeth whatsoever is prejudicial to truth, or injurious to our own or our neighbor's good name."},
		{"number":"79" , "question":"Which is the tenth commandment?", "answer":"The tenth commandment is, Thou shalt not covet thy neighbor's house, thou shalt not covet thy neighbor's wife, nor his manservant, nor his maidservant, nor his ox, nor his ass, nor anything that is thy neighbor's."},
		{"number":"80" , "question":"What is required in the tenth commandment?", "answer":"The tenth commandment requireth full contentment with our own condition, with a right and charitable frame of spirit toward our neighbor, and all that is his."},
		{"number":"81" , "question":"What is forbidden in the tenth commandment?", "answer":"The tenth commandment forbiddeth all discontentment with our own estate, envying or grieving at the good of our neighbor, and all inordinate motions and affections to anything that is his."},
		{"number":"82" , "question":"Is any man able perfectly to keep the commandments of God?", "answer":"No mere man since the fall is able in this life perfectly to keep the commandments of God, but doth daily break them in thought, word and deed."},
		{"number":"83" , "question":"Are all transgressions of the law equally heinous?", "answer":"Some sins in themselves, and by reason of several aggravations, are more heinous in the sight of God than others."},
		{"number":"84" , "question":"What doth every sin deserve?", "answer":"Every sin deserveth God's wrath and curse, both in this life, and that which is to come."},
		{"number":"85" , "question":"What doth God require of us that we may escape his wrath and curse due to us for sin?", "answer":"To escape the wrath and curse of God due to us for sin, God requireth of us faith in Jesus Christ, repentance unto life, with the diligent use of all the outward means whereby Christ communicateth to us the benefits of redemption."},
		{"number":"86" , "question":"What is faith in Jesus Christ?", "answer":"Faith in Jesus Christ is a saving grace, whereby we receive and rest upon him alone for salvation, as he is offered to us in the gospel."},
		{"number":"87" , "question":"What is repentance unto life?", "answer":"Repentance unto life is a saving grace, whereby a sinner, out of a true sense of his sin, and apprehension of the mercy of God in Christ, doth, with grief and hatred of his sin, turn from it unto God, with full purpose of, and endeavor after, new obedience."},
		{"number":"88" , "question":"What are the outward means whereby Christ communicateth to us the benefits of redemption?", "answer":"The outward and ordinary means whereby Christ communicateth to us the benefits of redemption, are his ordinances, especially the word, sacraments, and prayer; all which are made effectual to the elect for salvation."},
		{"number":"89" , "question":"How is the word made effectual to salvation?", "answer":"The Spirit of God maketh the reading, but especially the preaching, of the word, an effectual means of convincing and converting sinners, and of building them up in holiness and comfort, through faith, unto salvation."},
		{"number":"90" , "question":"How is the word to be read and heard, that it may become effectual to salvation?", "answer":"That the word may become effectual to salvation, we must attend thereunto with diligence, preparation and prayer; receive it with faith and love, lay it up in our hearts, and practice it in our lives."},
		{"number":"91" , "question":"How do the sacraments become effectual means of salvation?", "answer":"The sacraments become effectual means of salvation, not from any virtue in them, or in him that doth administer them; but only by the blessing of Christ, and the working of his Spirit in them that by faith receive them."},
		{"number":"93" , "question":"Which are the sacraments of the New Testament?", "answer":"The sacraments of the New Testament are baptism and the Lord's supper."},
		{"number":"94" , "question":"What is baptism?", "answer":"Baptism is a sacrament, wherein the washing with water in the name of the Father, and of the Son, and of the Holy Ghost, doth signify and seal our ingrafting into Christ, and partaking of the benefits of the covenant of grace, and our engagement to be the Lord's."},
		{"number":"95" , "question":"To whom is baptism to be administered?", "answer":"Baptism is not to be administered to any that are out of the visible church, till they profess their faith in Christ, and obedience to him; but the infants of such as are members of the visible church are to be baptized."},
		{"number":"96" , "question":"What is the Lord's supper?", "answer":"The Lord's supper is a sacrament, wherein, by giving and receiving bread and wine according to Christ's appointment, his death is showed forth; and the worthy receivers are, not after a corporal and carnal manner, but by faith, made partakers of his body and blood, with all his benefits, to their spiritual nourishment and growth in grace."},
		{"number":"97" , "question":"What is required to the worthy receiving of the Lord's supper?", "answer":"It is required of them that would worthily partake of the Lord's supper, that they examine themselves of their knowledge to discern the Lord's body, of their faith to feed upon him, of their repentance, love, and new obedience; lest, coming unworthily, they eat and drink judgment to themselves."},
		{"number":"98" , "question":"What is prayer?", "answer":"Prayer is an offering up of our desires unto God, for things agreeable to his will, in the name of Christ, with confession of our sins, and thankful acknowledgment of his mercies."},
		{"number":"99" , "question":"What rule hath God given for our direction in prayer?", "answer":"The whole word of God is of use to direct us in prayer; but the special rule of direction is that form of prayer which Christ taught his disciples, commonly called the Lord's prayer."},
		{"number":"100" , "question":"What doth the preface of the Lord's prayer teach us?", "answer":"The preface of the Lord's prayer, which is, Our Father which art in heaven, teacheth us to draw near to God with all holy reverence and confidence, as children to a father able and ready to help us; and that we should pray with and for others."},
		{"number":"101" , "question":"What do we pray for in the first petition?", "answer":"In the first petition, which is, Hallowed be thy name, we pray that God would enable us and others to glorify him in all that whereby he maketh himself known; and that he would dispose all things to his own glory."},
		{"number":"102" , "question":"What do we pray for in the second petition?", "answer":"In the second petition, which is, Thy kingdom come, we pray that Satan's kingdom may be destroyed; and that the kingdom of grace may be advanced, ourselves and others brought into it, and kept in it; and that the kingdom of glory may be hastened."},
		{"number":"103" , "question":"What do we pray for in the third petition?", "answer":"In the third petition, which is, Thy will be done in earth, as it is in heaven, we pray that God, by his grace, would make us able and willing to know, obey and submit to his will in all things, as the angels do in heaven."},
		{"number":"104" , "question":"What do we pray for in the fourth petition?", "answer":"In the fourth petition, which is, Give us this day our daily bread, we pray that of God's free gift we may receive a competent portion of the good things of this life, and enjoy his blessing with them."},
		{"number":"105" , "question":"What do we pray for in the fifth petition?", "answer":"In the fifth petition, which is, And forgive us our debts, as we forgive our debtors, we pray that God, for Christ's sake, would freely pardon all our sins; which we are the rather encouraged to ask, because by his grace we are enabled from the heart to forgive others."},
		{"number":"106" , "question":"What do we pray for in the sixth petition?", "answer":"In the sixth petition, which is, And lead us not into temptation, but deliver us from evil, we pray that God would either keep us from being tempted to sin, or support and deliver us when we are tempted."},
		{"number":"107" , "question":"What doth the conclusion of the Lord's prayer teach us?", "answer":"The conclusion of the Lord's prayer, which is, For thine is the kingdom, and the power, and the glory, forever, Amen, teacheth us to take our encouragement in prayer from God only, and in our prayers to praise him, ascribing kingdom, power and glory to him. And in testimony of our desire, and assurance to be heard, we say, Amen."}
	];
	
	for(var i=0;i<theCatechisms.length;i++){
		// create a catechism
		WestminsterCatechisms.insert(
			 theCatechisms[i]
		);
	}
}